---
# tasks file for user_del
- name: creating user
  user:
    name: "{{ uname }}"
    group: "{{ ugroup }}"
    password: "{{ upass }}" # | password_hash('sha512')}}"
    home: "{{uhome}}"
    state: present
